### ISSUE TITLE
Update composer requirements and release a new version

### ISSUE THREAD

**Issue by RobertLang** [rdoepner/cleverreach#12]
Could you release a new version with the composer requirements updated by @sschlein  ?

To widen up the use cases you could also set the requirements to
"guzzlehttp/guzzle": "^6.3|^7.0",
as this seems to be the only recent change and no changes have been made to the usage of guzzle.

Thanks,
Robert

**Comment by sschlein** [comment]
@RobertLang Sorry, aber wie groß ist bitte die Wahrscheinlichkeit, dass wir bei uns 5+ Jahre nach ORT in einem GitHub Repository wieder treffen?

**Comment by RobertLang** [comment]
@sschlein Die geht normalerweise so ziemlich gegen 0 ;-) Aber man kann eben auch nur die Aktiven wiedertreffen. :+1:

**Comment by rdoepner** [comment]
@RobertLang hab deine composer requirements hinzugefügt und als neue Version v1.6.0 getaggt.
