### ISSUE TITLE
Too strict requirement for Psr/Log

### ISSUE THREAD

**Issue by rvock** [rdoepner/cleverreach#7]
The commit 5cd32d417c1631cc0e861b6e7edada2d0170950e increased the requirement for `psr/log` from `^1.0` to `^1.1`.

This prevents the installation of this package in combination with other packages which have `psr/log` at `~1.0` (like symfony/cache).

I don't think you need `^1.1`, as there were no relevant changes (except test cases):
https://github.com/php-fig/log/compare/1.0.2...1.1.2

`^1.0` should work.

**Comment by yunosh** [comment]
`psr/log:~1.0` should work just fine, because it matches version 1.1 too. The only conflict would pop up if packages specified the single version constraint `psr/log:1.0` which is a bad idea and actually a problem of the other package.
